services:
  phpfpm:
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=8M
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0

  memcached:
    environment:
      - MEMCACHED_CACHE_SIZE=128

  nginx:
    environment:
      # Match PHP_UPLOAD_MAX_FILESIZE (plus a little more)
      NGINX_MAX_BODY_SIZE: 10M
