version: '3'

dotenv: [".task.env", ".env"]

tasks:
  template-prune:
    name: Prune installation
    desc: Update the repository's files to match current project name
    cmds:
      - |
        cat <<'EOF' > .env
        COMPOSE_PROJECT_NAME={{.PROJECTNAME}}
        COMPOSE_DOMAIN={{.PROJECTNAME}}.local.itkdev.dk
        EOF
      - rm -R web/themes/custom/TEMPLATE_THEME
      - |
        cat <<'EOF' >> deploy-templates/settings.local.php

        /**
         * Set trusted host pattern.
         */
        $settings['trusted_host_patterns'][] = '^{{.PROJECTNAME}}\.local\.itkdev\.dk$';
        EOF
      # Move Drupal configuration files into place.
      - mkdir -p web/sites/default
      - mv deploy-templates/{settings.local.php,services.local.yml} web/sites/default/

      - mv deploy-templates/pr.yml .github/workflows/

      # Set the actual project name in select files (Sed command different between mac and linux).
      - task rename

      # Move the rest of the files "here"
      - mv deploy-templates/* .
      # Remove deploy templates
      - rmdir deploy-templates
      # Remove workflows that make sense only in the template project
      - rm .github/workflows/template_*.yml

    requires:
      vars:
        - PROJECTNAME

    preconditions:
      - sh: "[[ {{.PROJECTNAME}} =~ ^[a-z0-9\\-]+$ ]]"
        msg: "PROJECTNAME should only contain lowercase a-z, digits and hyphens"

  docker:install:
      name: Install ITKDev docker compose
      desc: Install docker compose templates (to get the newest version)
      cmds:
        - itkdev-docker-compose template:install drupal-11 --force

  rename:
    cmds:
      - docker run --rm --volume=$PWD:/app itkdev/php8.3-fpm:latest sed -i -e 's/{PROJECTNAME}/{{.PROJECTNAME}}/g' README.md CHANGELOG.md
    platforms: ['darwin', 'linux']