version: '3'

dotenv: [".task.env", ".env"]

vars:
  DETECTED_OS:
    sh: |
      if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "linux-gnu"
      elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "darwin"
      elif [[ "$OSTYPE" == "cygwin" ]]; then
        echo "cygwin"
      elif [[ "$OSTYPE" == "msys" ]]; then
        echo "msys"
      elif [[ "$OSTYPE" == "win32" ]]; then
        echo "win32"
      elif [[ "$OSTYPE" == "freebsd"* ]]; then
        echo "freebsd"
      else
        echo "unknown"
      fi

tasks:
  template-prune:
    name: Prune installation
    desc: Update the repository's files to match current project name
    cmds:
      - echo $OSTYPE
      - |
        cat <<'EOF' > .env
        COMPOSE_PROJECT_NAME={{.PROJECTNAME}}
        COMPOSE_DOMAIN={{.PROJECTNAME}}.local.itkdev.dk
        EOF
      - rm -R web/themes/custom/TEMPLATE_THEME
      - |
        cat <<'EOF' >> deploy-templates/settings.local.php

        /**
         * Set trusted host pattern.
         */
        $settings['trusted_host_patterns'][] = '^{{.PROJECTNAME}}\.local\.itkdev\.dk$';
        EOF
      # Move Drupal configuration files into place.
      - mkdir -p web/sites/default
      - mv deploy-templates/{settings.local.php,services.local.yml} web/sites/default/

      - mv deploy-templates/pr.yml .github/workflows/
      # Move the rest of the files "here"
      - mv deploy-templates/* .
      # Set the actual project name in select files.
      - |
        if [[ "$OSTYPE" == linux-gnu* ]]; then
          sed -i -e 's/{PROJECTNAME}/{{.PROJECTNAME}}/g' README.md CHANGELOG.md
        elif [[ "$OSTYPE" == darwin* ]]; then
          sed -i '' -e 's/{PROJECTNAME}/{{.PROJECTNAME}}/g' README.md CHANGELOG.md
        else
          echo "Unknown OS!"
        fi
      - rmdir deploy-templates
      # Remove workflows that make sense only in the template project
      - rm .github/workflows/template_*.yml

    requires:
      vars:
        - PROJECTNAME

    preconditions:
      - sh: "[[ {{.PROJECTNAME}} =~ ^[a-z0-9\\-]+$ ]]"
        msg: "PROJECTNAME should only contain lowercase a-z, digits and hyphens"

  docker:install:
      name: Install ITKDev docker compose
      desc: Install docker compose templates (to get the newest version)
      cmds:
        - itkdev-docker-compose template:install drupal-10 --force
