version: '3'

dotenv: [".task.env", ".env"]

vars:
  DOCKER_COMPOSE: '{{ .TASK_DOCKER_COMPOSE | default "itkdev-docker-compose-server" }}'

tasks:

  build-site:new:
    cmds:
      - "{{.DOCKER_COMPOSE}} up --detach"
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer install"
      - sh -c "cp web/sites/default/default.settings.php web/sites/default/settings.php"
      - echo -e 'if (file_exists($app_root . "/" . $site_path . "/settings.local.php")) {\n  include $app_root . "/" . $site_path . "/settings.local.php";\n}' >> web/sites/default/settings.php
      - "{{.DOCKER_COMPOSE}} drush site-install minimal -y"

  build-site:existing-conf:
    cmds:
      - "{{.DOCKER_COMPOSE}} up --detach"
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer install"
      - "{{.DOCKER_COMPOSE}} drush site-install --existing-config --yes"

  simulate-github-actions:
    cmds:
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer normalize"
      - task check-code

  check-code:
    cmds:
      - docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint $(git ls-files *.md)
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer code-analysis"
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer coding-standards-check/twig-cs-fixer"