version: '3'

dotenv: [".task.env", ".env"]

vars:
  DOCKER_COMPOSE: '{{ .TASK_DOCKER_COMPOSE | default "itkdev-docker-compose-server" }}'

tasks:
  simulate-github-actions:
    cmds:
      - docker compose run --user root --rm phpfpm composer normalize
      - task check-code

  check-code:
    cmds:
      - docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint $(git ls-files *.md)
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer code-analysis"
      - "{{.DOCKER_COMPOSE}} exec phpfpm composer coding-standards-check/twig-cs-fixer"