name: Template test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0